import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<>
			<Head>
				<title>Virtual Agro - Eunápolis</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.container}>
				<main className={styles.main}></main>
				<main className={styles.title}>Virtual Agro🍉</main>

			</div>

		</>
	)
}
